version: "3.9"

services:
  nginx:
    build: requirements/nginx
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - wordpress
    restart: always
  wordpress:
    build: requirements/wordpress
    image: wordpress
    container_name: wordpress
    volumes: 
    - wp_data:/var/www/html
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always
  mariadb:
    build: requirements/mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: always

volumes:
    dbdata:
      # driver: local
      # driver_opts:
      #   type: none
      #   device: ./srcs/data/db
      #   o: bind
    wp_data:
      # driver: local
      # driver_opts:
      #   type: none
      #   device: /Users/omeslall/Desktop/inception/srcs/data/wp
      #   o: bind

networks:
  inception:
    driver: bridge